from enum import StrEnum


class AuditEventType(StrEnum):
    STATE_TRANSITION = "STATE_TRANSITION"
    FRAME_RECEIVED = "FRAME_RECEIVED"
    FRAME_DUPLICATE = "FRAME_DUPLICATE"
    FRAME_CONFLICT = "FRAME_CONFLICT"
    PAGE_CREATED = "PAGE_CREATED"
    CAPTURE_COMPLETE = "CAPTURE_COMPLETE"
    SESSION_LOCKED = "SESSION_LOCKED"
    GATE_1_EVALUATED = "GATE_1_EVALUATED"
    GATE_2_EVALUATED = "GATE_2_EVALUATED"
    OCR_COMPLETED = "OCR_COMPLETED"
    OCR_FALLBACK = "OCR_FALLBACK"
    LLM_ATTEMPT = "LLM_ATTEMPT"
    LLM_FALLBACK = "LLM_FALLBACK"
    ANSWER_FINALIZED = "ANSWER_FINALIZED"
    AUDIO_PUBLISHED = "AUDIO_PUBLISHED"
    RGB_RESULT_STATUS_CHANGED = "RGB_RESULT_STATUS_CHANGED"
    RGB_SEQUENCE_PUBLISHED = "RGB_SEQUENCE_PUBLISHED"
    RGB_SEQUENCE_EVENT_RECEIVED = "RGB_SEQUENCE_EVENT_RECEIVED"
    RGB_SEQUENCE_INVALID = "RGB_SEQUENCE_INVALID"
    INVALID_TRANSITION = "INVALID_TRANSITION"
    AUTH_FAILED = "AUTH_FAILED"
    STORAGE_ERROR = "STORAGE_ERROR"


class AuditStage(StrEnum):
    CAPTURE = "capture"
    IMAGE = "image"
    OCR = "ocr"
    RECONSTRUCTION = "reconstruction"
    GATE_1 = "gate_1"
    RAG = "rag"
    LLM = "llm"
    GATE_2 = "gate_2"
    AUDIO = "audio"
    SYSTEM = "system"
    AUTH = "auth"


class AuditSeverity(StrEnum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"
