from enum import StrEnum


class SessionState(StrEnum):
    CREATED = "CREATED"
    CAPTURING = "CAPTURING"
    CAPTURE_END_CANDIDATE = "CAPTURE_END_CANDIDATE"
    CAPTURE_LOCKING = "CAPTURE_LOCKING"
    LOCKED = "LOCKED"
    IMAGE_PROCESSING = "IMAGE_PROCESSING"
    OCR_PROCESSING = "OCR_PROCESSING"
    RECONSTRUCTING = "RECONSTRUCTING"
    RESCUE_PROCESSING = "RESCUE_PROCESSING"
    GATE_1 = "GATE_1"
    BLOCKED_GATE_1 = "BLOCKED_GATE_1"
    RAG_RETRIEVING = "RAG_RETRIEVING"
    SOLVING = "SOLVING"
    VERIFYING = "VERIFYING"
    ARBITRATING = "ARBITRATING"
    GATE_2 = "GATE_2"
    BLOCKED_GATE_2 = "BLOCKED_GATE_2"
    STATUS_AUDIO = "STATUS_AUDIO"
    TTS_GENERATING = "TTS_GENERATING"
    AUDIO_ASSEMBLING = "AUDIO_ASSEMBLING"
    AUDIO_VALIDATING = "AUDIO_VALIDATING"
    READY = "READY"
    COMPLETED = "COMPLETED"
    FAILED_RECOVERABLE = "FAILED_RECOVERABLE"
    FAILED_FATAL = "FAILED_FATAL"
    CANCELLED = "CANCELLED"

    @property
    def is_terminal(self) -> bool:
        return self in {SessionState.COMPLETED, SessionState.FAILED_FATAL, SessionState.CANCELLED}
