from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    # Generic
    UNKNOWN = "UNKNOWN"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    RATE_LIMITED = "RATE_LIMITED"

    # Idempotency
    IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD = "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD"

    # Session / state
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_LOCKED = "SESSION_LOCKED"
    SESSION_CANCELLED = "SESSION_CANCELLED"
    SESSION_FAILED = "SESSION_FAILED"

    # Capture
    CAPTURE_NOT_FOUND = "CAPTURE_NOT_FOUND"
    CAPTURE_INCOMPLETE = "CAPTURE_INCOMPLETE"
    CAPTURE_DUPLICATE = "CAPTURE_DUPLICATE"
    CAPTURE_TIMEOUT = "CAPTURE_TIMEOUT"

    # Frame
    FRAME_HASH_MISMATCH = "FRAME_HASH_MISMATCH"
    FRAME_DUPLICATE_CONFLICT = "FRAME_DUPLICATE_CONFLICT"
    FRAME_INVALID_MIME = "FRAME_INVALID_MIME"
    FRAME_TOO_LARGE = "FRAME_TOO_LARGE"
    FRAME_INVALID_DIMENSIONS = "FRAME_INVALID_DIMENSIONS"
    FRAME_INVALID_MAGIC_BYTES = "FRAME_INVALID_MAGIC_BYTES"

    # Storage
    STORAGE_UPLOAD_FAILED = "STORAGE_UPLOAD_FAILED"
    STORAGE_DOWNLOAD_FAILED = "STORAGE_DOWNLOAD_FAILED"
    STORAGE_OBJECT_NOT_FOUND = "STORAGE_OBJECT_NOT_FOUND"
    STORAGE_OVERWRITE_FORBIDDEN = "STORAGE_OVERWRITE_FORBIDDEN"
    STORAGE_TIMEOUT = "STORAGE_TIMEOUT"
    STORAGE_ORPHAN_CREATED = "STORAGE_ORPHAN_CREATED"

    # Auth
    GATEWAY_AUTH_FAILED = "GATEWAY_AUTH_FAILED"
    GATEWAY_DISABLED = "GATEWAY_DISABLED"
    DEVICE_AUTH_FAILED = "DEVICE_AUTH_FAILED"
    DEVICE_UNKNOWN = "DEVICE_UNKNOWN"
    DEVICE_DISABLED = "DEVICE_DISABLED"
    DEVICE_REPLAY_DETECTED = "DEVICE_REPLAY_DETECTED"

    # Page / logical
    NO_USABLE_FRAME = "NO_USABLE_FRAME"
    LOGICAL_PAGE_LIMIT_REACHED = "LOGICAL_PAGE_LIMIT_REACHED"
    END_MARKER_DETECTED = "END_MARKER_DETECTED"

    # OCR
    OCR_PROVIDER_TIMEOUT = "OCR_PROVIDER_TIMEOUT"
    OCR_PROVIDER_UNAVAILABLE = "OCR_PROVIDER_UNAVAILABLE"
    OCR_PROVIDER_ERROR = "OCR_PROVIDER_ERROR"
    OCR_PROVIDER_RATE_LIMITED = "OCR_PROVIDER_RATE_LIMITED"
    OCR_PROVIDER_AUTH_ERROR = "OCR_PROVIDER_AUTH_ERROR"
    OCR_PROVIDER_DISABLED = "OCR_PROVIDER_DISABLED"
    OCR_CIRCUIT_BREAKER_OPEN = "OCR_CIRCUIT_BREAKER_OPEN"
    OCR_LOW_CONFIDENCE = "OCR_LOW_CONFIDENCE"
    OCR_SCHEMA_INVALID = "OCR_SCHEMA_INVALID"
    OCR_INVALID_REQUEST = "OCR_INVALID_REQUEST"
    OCR_INVALID_RESPONSE = "OCR_INVALID_RESPONSE"
    OCR_ALL_PROVIDERS_FAILED = "OCR_ALL_PROVIDERS_FAILED"

    # Reconstruction
    QUESTION_NUMBER_MISSING = "QUESTION_NUMBER_MISSING"
    QUESTION_ALTERNATIVES_INCOMPLETE = "QUESTION_ALTERNATIVES_INCOMPLETE"
    QUESTION_VISUAL_AMBIGUITY = "QUESTION_VISUAL_AMBIGUITY"
    QUESTION_DUPLICATE_NUMBER = "QUESTION_DUPLICATE_NUMBER"
    QUESTION_SEQUENCE_GAP = "QUESTION_SEQUENCE_GAP"
    RECONSTRUCTION_RESCUE_BUDGET_EXCEEDED = "RECONSTRUCTION_RESCUE_BUDGET_EXCEEDED"
    RECONSTRUCTION_SCHEMA_INVALID = "RECONSTRUCTION_SCHEMA_INVALID"

    # Gate
    GATE_1_BLOCKED = "GATE_1_BLOCKED"
    GATE_2_BLOCKED = "GATE_2_BLOCKED"

    # Firmware V2.2 RGB result channel
    RGB_RESULTS_DISABLED = "RGB_RESULTS_DISABLED"
    RGB_SEQUENCE_INCOMPLETE = "RGB_SEQUENCE_INCOMPLETE"
    RGB_SEQUENCE_INVALID = "RGB_SEQUENCE_INVALID"
    RGB_SEQUENCE_NOT_FOUND = "RGB_SEQUENCE_NOT_FOUND"
    RGB_SEQUENCE_CONFLICT = "RGB_SEQUENCE_CONFLICT"
    RGB_SEQUENCE_ALREADY_COMPLETED = "RGB_SEQUENCE_ALREADY_COMPLETED"

    # LLM
    LLM_TIMEOUT = "LLM_TIMEOUT"
    LLM_RATE_LIMITED = "LLM_RATE_LIMITED"
    LLM_PROVIDER_ERROR = "LLM_PROVIDER_ERROR"
    LLM_SCHEMA_INVALID = "LLM_SCHEMA_INVALID"
    LLM_SCHEMA_REPAIR_FAILED = "LLM_SCHEMA_REPAIR_FAILED"
    LLM_ANSWER_INVALID_ALTERNATIVE = "LLM_ANSWER_INVALID_ALTERNATIVE"
    LLM_ALL_PROVIDERS_FAILED = "LLM_ALL_PROVIDERS_FAILED"
    ARBITRATION_UNRESOLVED = "ARBITRATION_UNRESOLVED"

    # Audio / TTS
    TTS_PROVIDER_FAILED = "TTS_PROVIDER_FAILED"
    TTS_TIMEOUT = "TTS_TIMEOUT"
    TTS_ALL_PROVIDERS_FAILED = "TTS_ALL_PROVIDERS_FAILED"
    AUDIO_VALIDATION_FAILED = "AUDIO_VALIDATION_FAILED"
    AUDIO_DURATION_INVALID = "AUDIO_DURATION_INVALID"
    AUDIO_SILENCE_MISSING = "AUDIO_SILENCE_MISSING"
    AUDIO_FFMPEG_FAILED = "AUDIO_FFMPEG_FAILED"

    # Knowledge / RAG
    KNOWLEDGE_NOT_FOUND = "KNOWLEDGE_NOT_FOUND"
    KNOWLEDGE_DOCUMENT_EXISTS = "KNOWLEDGE_DOCUMENT_EXISTS"
    KNOWLEDGE_EXTRACTION_FAILED = "KNOWLEDGE_EXTRACTION_FAILED"
    KNOWLEDGE_UNSUPPORTED_FORMAT = "KNOWLEDGE_UNSUPPORTED_FORMAT"
    KNOWLEDGE_EMBEDDING_FAILED = "KNOWLEDGE_EMBEDDING_FAILED"
    KNOWLEDGE_REINDEX_FAILED = "KNOWLEDGE_REINDEX_FAILED"
    EMBEDDING_PROVIDER_TIMEOUT = "EMBEDDING_PROVIDER_TIMEOUT"
    EMBEDDING_PROVIDER_ERROR = "EMBEDDING_PROVIDER_ERROR"
    EMBEDDING_PROVIDER_AUTH_ERROR = "EMBEDDING_PROVIDER_AUTH_ERROR"
    RETRIEVAL_FAILED = "RETRIEVAL_FAILED"

    # Temp / disk
    TEMP_QUOTA_EXCEEDED = "TEMP_QUOTA_EXCEEDED"


class AppError(Exception):
    def __init__(
        self,
        message: str,
        reason_code: ReasonCode = ReasonCode.INTERNAL_ERROR,
        *,
        http_status: int = 500,
    ) -> None:
        super().__init__(message)
        self.reason_code = reason_code
        self.http_status = http_status


class RetryableError(AppError):
    pass


class NonRetryableError(AppError):
    pass


class InvalidStateTransition(NonRetryableError):  # noqa: N818
    def __init__(self, from_state: str, to_state: str) -> None:
        super().__init__(
            f"Cannot transition from {from_state} to {to_state}",
            reason_code=ReasonCode.INVALID_STATE_TRANSITION,
            http_status=409,
        )
        self.from_state = from_state
        self.to_state = to_state


class StorageError(RetryableError):
    pass


class StorageOverwriteForbidden(NonRetryableError):  # noqa: N818
    def __init__(self, bucket: str, key: str) -> None:
        super().__init__(
            f"Overwrite forbidden for {bucket}/{key}",
            reason_code=ReasonCode.STORAGE_OVERWRITE_FORBIDDEN,
            http_status=409,
        )


class AuthError(NonRetryableError):
    def __init__(self, message: str, reason_code: ReasonCode = ReasonCode.UNAUTHORIZED) -> None:
        super().__init__(message, reason_code=reason_code, http_status=401)


class FrameConflictError(NonRetryableError):
    def __init__(self, reason_code: ReasonCode, message: str) -> None:
        super().__init__(message, reason_code=reason_code, http_status=409)
