"use client";
import { useParams } from "next/navigation";
import Image from "next/image";
import { useEffect, useState } from "react";
import { apiFetch, ApiError } from "@/lib/api";
import { formatDate } from "@/lib/date";

type Frame={frame_id:string;capture_id:string;frame_index:number;storage_key:string;sha256:string;width:number|null;height:number|null;orientation:number|null;resolution:string|null;created_at:string};
type Answer={question_number:number;status:string;answer:string|null;validated:boolean;color:{letter:string;rgb:number[]}|null};
type Log={event_type:string;stage:string;severity:string;reason_code:string|null;actor_type:string|null;payload:Record<string,unknown>|null;created_at:string};
type Detail={public_id:string;session_type:string;status:string;created_at:string;updated_at:string;expected_pages:number;expected_questions:number;minimum_ratio:number;capture_source:string;settings_version:number;device_code:string;gateway_code:string;frames:Frame[];answers:Answer[];rgb_sequence:{sequence_id:string;revision:number;status:string;answers:string;item_count:number;defaults:Record<string,number>;palette:Record<string,unknown>;sha256:string;payload_size:number}|null;delivery:Record<string,unknown>|null;logs:Log[]};

export default function DetailPage(){
 const {id}=useParams<{id:string}>(); const [d,setD]=useState<Detail|null>(null); const [tab,setTab]=useState<"fotos"|"cores"|"logs">("fotos"); const [photo,setPhoto]=useState<{url:string;frame:Frame}|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 async function load(){try{setD(await apiFetch<Detail>(`/api/v1/admin/sessions/${id}`));setError("");}catch(e){setError(e instanceof ApiError?e.message:"Falha ao carregar");}}
 useEffect(()=>{load();},[id]); // eslint-disable-line react-hooks/exhaustive-deps
 async function openPhoto(frame:Frame){try{const r=await apiFetch<{url:string}>(`/api/v1/admin/sessions/${id}/frames/${frame.frame_id}/url`);setPhoto({url:r.url,frame});}catch(e){setError(e instanceof ApiError?e.message:"Falha na foto");}}
 async function action(kind:"cancel"|"retry"){const reason=window.prompt(kind==="cancel"?"Motivo do cancelamento":"Motivo do reprocessamento");if(!reason)return;setBusy(true);try{await apiFetch(`/api/v1/admin/sessions/${id}/${kind}`,{method:"POST",headers:kind==="retry"?{"Idempotency-Key":crypto.randomUUID()}:undefined,body:JSON.stringify({reason})});await load();}catch(e){setError(e instanceof ApiError?e.message:"Falha na ação");}finally{setBusy(false);}}
 if(!d)return <div className="p-8 text-zinc-400">{error||"Carregando…"}</div>;
 return <div className="mx-auto max-w-7xl space-y-5 p-4 md:p-6">
  {error&&<div role="alert" className="rounded-lg border border-red-900 bg-red-950/40 p-3 text-red-300">{error}</div>}
  <section className="card"><div className="flex flex-wrap items-start gap-3"><div className="mr-auto"><h1 className="font-mono text-lg">{d.public_id}</h1><p className="text-sm text-zinc-400">{d.session_type} • {d.status} • {formatDate(d.created_at)}</p></div><button disabled={busy} onClick={()=>action("retry")} className="secondary">Reprocessar</button><button disabled={busy} onClick={()=>action("cancel")} className="primary">Cancelar</button></div>
   <div className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-5">{[["Fotos",d.frames.length],["Questões",`${d.answers.length}/${d.expected_questions}`],["RGB",d.rgb_sequence?`${d.rgb_sequence.item_count} cores`:"—"],["Settings",`v${d.settings_version}`],["SHA",d.rgb_sequence?`${d.rgb_sequence.sha256.slice(0,12)}…`:"—"]].map(([a,b])=><div key={a} className="rounded-lg bg-[#242424] p-3"><span className="block text-xs text-zinc-500">{a}</span>{b}</div>)}</div>
  </section>
  <div className="flex gap-2" role="tablist">{([['fotos','Fotos'],['cores','Cores (RGB)'],['logs','Registros']] as const).map(([k,l])=><button role="tab" aria-selected={tab===k} key={k} onClick={()=>setTab(k)} className={tab===k?"primary":"secondary"}>{l}</button>)}</div>
  {tab==="fotos"&&<section className="grid gap-3 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-5">{d.frames.map(f=><article className="card" key={f.frame_id}><p className="text-sm">Frame {f.frame_index}</p><p className="truncate text-xs text-zinc-500">{f.sha256}</p><button onClick={()=>openPhoto(f)} className="secondary mt-3 w-full">Ver foto</button><p className="mt-2 truncate text-[10px] text-zinc-600">{f.storage_key}</p></article>)}{!d.frames.length&&<p className="text-zinc-500">Nenhuma foto.</p>}</section>}
  {tab==="cores"&&<section className="space-y-2">{d.answers.map(a=><div className="card flex items-center gap-3" key={a.question_number}><span className="w-10">Q{a.question_number}</span><span className="h-7 w-7 rounded" style={{background:a.color?`rgb(${a.color.rgb.join(',')})`:"#333"}}/><span>{a.answer||"—"} {a.color&&`• ${a.color.rgb.join(", ")}`}</span><span className="ml-auto text-xs text-zinc-500">{a.validated?"Validada":a.status}</span></div>)}{d.rgb_sequence&&<pre className="card overflow-auto text-xs">{JSON.stringify(d.rgb_sequence,null,2)}</pre>}</section>}
  {tab==="logs"&&<section className="space-y-2">{d.logs.map((l,i)=><details className="card" key={`${l.created_at}-${i}`}><summary className="cursor-pointer text-sm"><span className="font-mono text-xs text-zinc-400">{formatDate(l.created_at)}</span> • {l.event_type} • {l.stage}</summary><pre className="mt-3 overflow-auto text-xs text-zinc-400">{JSON.stringify(l.payload,null,2)}</pre></details>)}{!d.logs.length&&<p className="text-zinc-500">Sem registros.</p>}</section>}
  {photo&&<div role="dialog" aria-modal="true" aria-label="Foto ampliada" className="fixed inset-0 z-50 grid place-items-center bg-black/85 p-4" onClick={()=>setPhoto(null)}><div className="max-h-full max-w-5xl rounded-xl bg-[#1A1A1A] p-4" onClick={e=>e.stopPropagation()}><button autoFocus onClick={()=>setPhoto(null)} className="secondary mb-3">Fechar</button><Image src={photo.url} alt={`Frame ${photo.frame.frame_index}`} width={1600} height={1200} unoptimized className="max-h-[70vh] max-w-full object-contain"/><p className="mt-2 text-xs text-zinc-400">SHA {photo.frame.sha256} • {photo.frame.resolution||`${photo.frame.width||'?'}x${photo.frame.height||'?'}`} • orientação {photo.frame.orientation??0}</p></div></div>}
 </div>;
}
