"use client";
import { useEffect, useState } from "react";
import { apiFetch, ApiError } from "@/lib/api";
type Color={rgb:number[]}; type Palette=Record<string,Color>;
type Settings={version:number;ocr_provider:string;solve_model:string;verify_model:string;arbiter_model:string;deepseek_configured:boolean;gemini_configured:boolean;anthropic_configured:boolean;glm_configured:boolean;expected_pages:number;expected_questions:number;handwritten_expected_questions:number;minimum_ratio:number;brightness_percent:number;on_ms:number;off_ms:number;palette:Palette;handwritten_palette:Palette};
const models=["deepseek-v4-pro","gemini-3.1-pro","claude-opus-5","glm-5.3"];
const keyRows=[['deepseek','DeepSeek'],['gemini','Gemini'],['anthropic','Claude'],['glm','GLM']] as const;
function hex(rgb:number[]){return `#${rgb.map(x=>x.toString(16).padStart(2,'0')).join('')}`;}
function fromHex(v:string){return [1,3,5].map(i=>parseInt(v.slice(i,i+2),16));}
export default function ConfigPage(){
 const [s,setS]=useState<Settings|null>(null),[keys,setKeys]=useState<Record<string,string>>({}),[msg,setMsg]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{setS(await apiFetch<Settings>("/api/v1/admin/settings"));}catch(e){setError(e instanceof ApiError?e.message:"Falha ao carregar");}}
 useEffect(()=>{load();},[]);
 async function save(){if(!s)return;setBusy(true);setError("");try{const payload={version:s.version,ocr_provider:s.ocr_provider,solve_model:s.solve_model,verify_model:s.verify_model,arbiter_model:s.arbiter_model,expected_pages:s.expected_pages,expected_questions:s.expected_questions,handwritten_expected_questions:s.handwritten_expected_questions,minimum_ratio:s.minimum_ratio,brightness_percent:s.brightness_percent,on_ms:s.on_ms,off_ms:s.off_ms,palette:s.palette,handwritten_palette:s.handwritten_palette,...Object.fromEntries(Object.entries(keys).filter(([,v])=>v).map(([k,v])=>[`${k}_api_key`,v]))};setS(await apiFetch<Settings>("/api/v1/admin/settings",{method:"PUT",body:JSON.stringify(payload)}));setKeys({});setMsg("Configurações salvas. Novas sessões usarão esta versão.");}catch(e){setError(e instanceof ApiError?(e.status===409?"Outra aba alterou os dados. Recarregue e tente novamente.":e.message):"Falha ao salvar");}finally{setBusy(false);}}
 async function testProvider(name:string){const map:Record<string,string>={deepseek:"deepseek-v4-pro",gemini:"gemini-3.1-pro",anthropic:"claude-opus-5",glm:"glm-5.3"};const provider=name==="anthropic"?"claude":name;try{const r=await apiFetch<{ok:boolean;latency_ms:number;message?:string}>("/api/v1/admin/settings/test",{method:"POST",body:JSON.stringify({provider,model:map[name]})});setMsg(r.ok?`${name}: conectado em ${r.latency_ms} ms`:`${name}: ${r.message}`);}catch(e){setError(e instanceof ApiError?e.message:"Falha no teste");}}
 function field(key:keyof Settings,value:unknown){if(s)setS({...s,[key]:value});}
 function palette(which:"palette"|"handwritten_palette",letter:string,rgb:number[]){if(s)setS({...s,[which]:{...s[which],[letter]:{rgb}}});}
 if(!s)return <div className="p-8 text-zinc-400">{error||"Carregando…"}</div>;
 return <div className="mx-auto max-w-5xl space-y-6 p-4 md:p-6"><div><h1 className="text-2xl font-semibold">Configurações</h1><p className="text-sm text-zinc-400">Versão {s.version}. Mudanças afetam somente novas sessões.</p></div>{error&&<p role="alert" className="rounded-lg border border-red-900 p-3 text-red-300">{error}</p>}{msg&&<p role="status" className="rounded-lg border border-emerald-900 p-3 text-emerald-300">{msg}</p>}
  <section className="card space-y-4"><h2 className="font-medium">Modelos e Chaves</h2>{([['ocr_provider','Modelo que lê a foto (OCR)',['google_document_ai','azure','paddle']],['solve_model','Modelo que resolve',models],['verify_model','Modelo que confere',models],['arbiter_model','Modelo que decide',models]] as [keyof Settings,string,string[]][]).map(([k,l,opts])=><label key={k} className="grid gap-2 text-sm md:grid-cols-[250px_1fr]"><span>{l}</span><select className="control" value={String(s[k])} onChange={e=>field(k,e.target.value)}>{opts.map(o=><option key={o}>{o}</option>)}</select></label>)}
   {keyRows.map(([k,l])=><div key={k} className="grid items-center gap-2 md:grid-cols-[250px_1fr_auto]"><label className="text-sm" htmlFor={`key-${k}`}>{l} — {(s as unknown as Record<string,boolean>)[`${k}_configured`]?"Configurada":"Não configurada"}</label><input id={`key-${k}`} type="password" autoComplete="off" className="control" value={keys[k]||""} onChange={e=>setKeys({...keys,[k]:e.target.value})} placeholder="Deixe vazio para preservar"/><button onClick={()=>testProvider(k)} className="secondary">Verificar</button></div>)}
  </section>
  <section className="card space-y-5"><h2 className="font-medium">Prova e Cores</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{([['expected_pages','Páginas EXAM'],['expected_questions','Questões EXAM'],['handwritten_expected_questions','Fotos manuscrito'],['minimum_ratio','Mínimo RGB (0–1)'],['brightness_percent','Brilho %'],['on_ms','Ligado ms'],['off_ms','Desligado ms']] as [keyof Settings,string][]).map(([k,l])=><label key={k} className="text-sm">{l}<input className="control mt-1" type="number" step={k==='minimum_ratio'?'0.01':'1'} value={Number(s[k])} onChange={e=>field(k,Number(e.target.value))}/></label>)}</div>
   {([['palette','Paleta Prova'],['handwritten_palette','Paleta Manuscrito']] as const).map(([which,title])=><div key={which}><h3 className="mb-2 text-sm text-zinc-300">{title}</h3><div className="grid gap-2 sm:grid-cols-5">{"ABCDE".split('').map(letter=><label key={letter} className="rounded-lg bg-[#242424] p-3 text-sm"><span className="mb-2 block">{letter} • {s[which][letter].rgb.join(',')}</span><input className="h-10 w-full" type="color" value={hex(s[which][letter].rgb)} onChange={e=>palette(which,letter,fromHex(e.target.value))}/></label>)}</div></div>)}
   <div><h3 className="mb-2 text-sm">Preview</h3><div className="flex flex-wrap gap-2">{Array.from({length:10},(_,i)=>"ABCDE"[i%5]).map((l,i)=><span key={i} title={`Q${i+1} ${l}`} className="h-9 w-9 rounded-lg border border-white/10 motion-safe:animate-pulse" style={{background:`rgb(${s.handwritten_palette[l].rgb.join(',')})`,opacity:s.brightness_percent/100}}/>)}</div></div>
  </section><button disabled={busy} onClick={save} className="primary w-full py-3">{busy?"Salvando…":"Salvar configurações"}</button>
 </div>;
}
